BASICS OF DATA STRUCTURES AND ALGORITHMS

ARRAYS: It is defined as the collection of similar types of data items stored at contiguous memory locations. It is basically stores multiple items of a same type together.

Properties of ARRAYS:
1. Arrays can store data of a specified type. 
2. Elements of an array are located in a contiguous. 
3. Each element of an array has a unique index.
4. The size of an array is predefined and cannot be modified.

AN ARRAY IS A DATA STRUCTURE CONSISTING OF A COLLECTION OF ELEMENTS EACH IDENTIFIED BY ATLEAST ONE ARRAY INDEX OR KEY. AN ARRAY IS STORED SUCH THAT THE POSITION OF EACH ELEMENT CAN BE COMPUTED FROM ITS INDEX BY A MATHEMATICAL FORMULA. 

TYPES OF ARRAYS:
1. ONE DIMENSIONAL ARRAY: It is an array with a bunch of values having been declared with a single index. a[i] between 0 and n.
2. TWO DIMENSIONAL ARRAY: An array with a bunch of values having been declared with a double index. a[i] [j]-> i and j between 0 and n.
3. THREE DIMENSIONAL ARRAY: An array with a bunch of values having been declared with a triple index. 
a[i][j][k]-> i,j,k between 0 and n. a[0][0][1] where i = depth, j = row, k = column.


IMPORTANT NOTE: AN ARRAY ELEMENTS MUST ALWAYS BE LOCATED NEXT TO EACH OTHER IN THE MEMORY.

TWO DIMENSIONAL ARRAY: An array with a bunch of values having been declared with double index. a[i][j]-> i and j between 0 and n. It can also be defined as a collection of 1-Dimensional Arrays. Mostly used in Matrix operations. i denotes row number and j denotes column number.

When we create an arrays following are the steps to be followed:
1. Assign it to a variable
2. Define the type of elements that it will store.
3. Define it's size (the maximum number of elements)

Create a 2_D Array

In [1]:
import numpy as np

twoDarray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDarray)

#Time Complexity = O(1)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


Insertion-Two Dimensional Array

Adding a Column in a 2-D Array: We use the numpy library as np. So the expression goes about "np.insert(<arrayname>,<position of row or column we are adding>,<have double brackets and add the values you need to add>, <select axis parameter it can be 0 for row and 1 for adding column>)

In [3]:
new2Darray = np.insert(twoDarray, 0,[[1,2,3,4]], axis = 1)
print(new2Darray)


new2Darray = np.insert(twoDarray, 0,[[21,22,23,24]], axis = 0)
print(new2Darray)



[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]
[[21 22 23 24]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


We can also use the append method to insert into array but that way only the last row or column can be selected.

In [5]:
new2Darray1 = np.append(new2Darray,[[31,32,33,34]],axis = 0) ####Always appends last most row or column. No need to mention position
print(new2Darray1)

[[21 22 23 24]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [31 32 33 34]]


Access an Element of Two Dimensional Array. a[i][j] where i is the row index and j is the column index. Index for both starts from 0.

In [7]:
# lets make a new array
newarr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,0],[15,18,14,9]])
print(newarr)

def accessElements(array,rowIndex,columnIndex):
    if rowIndex >= len(array) and columnIndex >= len(array[0]):  
        print("The inncorrect Index ")
    else:
        print(array[rowIndex][columnIndex])

accessElements(newarr,2,1)

## TIME COMPLEXITY: O(1)
## SPACE COMPLEXITY: O(1)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  0]
 [15 18 14  9]]
17


Traversal of a 2 Dimensional Array

In [8]:
def traverse2Darray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

traverse2Darray(newarr)

11
15
10
6
10
14
11
5
12
17
12
0
15
18
14
9


Searching elements in a 2-Dimensional Array. We will follow the linear search method to search the array.

In [9]:
print(newarr)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  0]
 [15 18 14  9]]


In [13]:
def search2Darray(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return "The element is found "+str(i)+" "+str(j)
    return "The element is not found"
print(search2Darray(newarr,17))

### Time Complexity is O(MN)

The element is found 2 1


Delete elements for Two Dimensional Array

In [15]:
newarr = np.delete(newarr, 0, axis = 0)
print(newarr)

newarr = np.delete(newarr, 0, axis = 1)
print(newarr)

###Time Complexity is O(mn)
###Space Complexity is O(1)

[[12 17 12  0]
 [15 18 14  9]]
[[17 12  0]
 [18 14  9]]
